//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_FinalWork.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfModel_movies", Namespace="http://tempuri.org/", ItemName="model_movies")]
    [System.SerializableAttribute()]
    public class ArrayOfModel_movies : System.Collections.Generic.List<CSharp_FinalWork.WebService.model_movies> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="model_movies", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class model_movies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Times {
            get {
                return this.TimesField;
            }
            set {
                if ((object.ReferenceEquals(this.TimesField, value) != true)) {
                    this.TimesField = value;
                    this.RaisePropertyChanged("Times");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Rate {
            get {
                return this.RateField;
            }
            set {
                if ((object.ReferenceEquals(this.RateField, value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Actor {
            get {
                return this.ActorField;
            }
            set {
                if ((object.ReferenceEquals(this.ActorField, value) != true)) {
                    this.ActorField = value;
                    this.RaisePropertyChanged("Actor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="model_detail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class model_detail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescribeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Describe {
            get {
                return this.DescribeField;
            }
            set {
                if ((object.ReferenceEquals(this.DescribeField, value) != true)) {
                    this.DescribeField = value;
                    this.RaisePropertyChanged("Describe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Actor {
            get {
                return this.ActorField;
            }
            set {
                if ((object.ReferenceEquals(this.ActorField, value) != true)) {
                    this.ActorField = value;
                    this.RaisePropertyChanged("Actor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfModel_moviecrude", Namespace="http://tempuri.org/", ItemName="model_moviecrude")]
    [System.SerializableAttribute()]
    public class ArrayOfModel_moviecrude : System.Collections.Generic.List<CSharp_FinalWork.WebService.model_moviecrude> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="model_moviecrude", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class model_moviecrude : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfModel_movies_coming", Namespace="http://tempuri.org/", ItemName="model_movies_coming")]
    [System.SerializableAttribute()]
    public class ArrayOfModel_movies_coming : System.Collections.Generic.List<CSharp_FinalWork.WebService.model_movies_coming> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="model_movies_coming", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class model_movies_coming : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Times {
            get {
                return this.TimesField;
            }
            set {
                if ((object.ReferenceEquals(this.TimesField, value) != true)) {
                    this.TimesField = value;
                    this.RaisePropertyChanged("Times");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 MessageResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        CSharp_FinalWork.WebService.MessageResponse Message(CSharp_FinalWork.WebService.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MessageResponse> MessageAsync(CSharp_FinalWork.WebService.MessageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 link 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MessageDetail", ReplyAction="*")]
        CSharp_FinalWork.WebService.MessageDetailResponse MessageDetail(CSharp_FinalWork.WebService.MessageDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MessageDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MessageDetailResponse> MessageDetailAsync(CSharp_FinalWork.WebService.MessageDetailRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 link 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RelatedMovies", ReplyAction="*")]
        CSharp_FinalWork.WebService.RelatedMoviesResponse RelatedMovies(CSharp_FinalWork.WebService.RelatedMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RelatedMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.RelatedMoviesResponse> RelatedMoviesAsync(CSharp_FinalWork.WebService.RelatedMoviesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 link 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieAssess", ReplyAction="*")]
        CSharp_FinalWork.WebService.MovieAssessResponse MovieAssess(CSharp_FinalWork.WebService.MovieAssessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MovieAssess", ReplyAction="*")]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MovieAssessResponse> MovieAssessAsync(CSharp_FinalWork.WebService.MovieAssessRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Message_comingResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message_coming", ReplyAction="*")]
        CSharp_FinalWork.WebService.Message_comingResponse Message_coming(CSharp_FinalWork.WebService.Message_comingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message_coming", ReplyAction="*")]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.Message_comingResponse> Message_comingAsync(CSharp_FinalWork.WebService.Message_comingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Message", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.MessageRequestBody Body;
        
        public MessageRequest() {
        }
        
        public MessageRequest(CSharp_FinalWork.WebService.MessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MessageRequestBody {
        
        public MessageRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.MessageResponseBody Body;
        
        public MessageResponse() {
        }
        
        public MessageResponse(CSharp_FinalWork.WebService.MessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSharp_FinalWork.WebService.ArrayOfModel_movies MessageResult;
        
        public MessageResponseBody() {
        }
        
        public MessageResponseBody(CSharp_FinalWork.WebService.ArrayOfModel_movies MessageResult) {
            this.MessageResult = MessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageDetail", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.MessageDetailRequestBody Body;
        
        public MessageDetailRequest() {
        }
        
        public MessageDetailRequest(CSharp_FinalWork.WebService.MessageDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string link;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tag;
        
        public MessageDetailRequestBody() {
        }
        
        public MessageDetailRequestBody(string link, int tag) {
            this.link = link;
            this.tag = tag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.MessageDetailResponseBody Body;
        
        public MessageDetailResponse() {
        }
        
        public MessageDetailResponse(CSharp_FinalWork.WebService.MessageDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSharp_FinalWork.WebService.model_detail MessageDetailResult;
        
        public MessageDetailResponseBody() {
        }
        
        public MessageDetailResponseBody(CSharp_FinalWork.WebService.model_detail MessageDetailResult) {
            this.MessageDetailResult = MessageDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RelatedMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RelatedMovies", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.RelatedMoviesRequestBody Body;
        
        public RelatedMoviesRequest() {
        }
        
        public RelatedMoviesRequest(CSharp_FinalWork.WebService.RelatedMoviesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RelatedMoviesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string link;
        
        public RelatedMoviesRequestBody() {
        }
        
        public RelatedMoviesRequestBody(string link) {
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RelatedMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RelatedMoviesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.RelatedMoviesResponseBody Body;
        
        public RelatedMoviesResponse() {
        }
        
        public RelatedMoviesResponse(CSharp_FinalWork.WebService.RelatedMoviesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RelatedMoviesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSharp_FinalWork.WebService.ArrayOfModel_moviecrude RelatedMoviesResult;
        
        public RelatedMoviesResponseBody() {
        }
        
        public RelatedMoviesResponseBody(CSharp_FinalWork.WebService.ArrayOfModel_moviecrude RelatedMoviesResult) {
            this.RelatedMoviesResult = RelatedMoviesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieAssessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieAssess", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.MovieAssessRequestBody Body;
        
        public MovieAssessRequest() {
        }
        
        public MovieAssessRequest(CSharp_FinalWork.WebService.MovieAssessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MovieAssessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string link;
        
        public MovieAssessRequestBody() {
        }
        
        public MovieAssessRequestBody(string link) {
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MovieAssessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MovieAssessResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.MovieAssessResponseBody Body;
        
        public MovieAssessResponse() {
        }
        
        public MovieAssessResponse(CSharp_FinalWork.WebService.MovieAssessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MovieAssessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSharp_FinalWork.WebService.ArrayOfString MovieAssessResult;
        
        public MovieAssessResponseBody() {
        }
        
        public MovieAssessResponseBody(CSharp_FinalWork.WebService.ArrayOfString MovieAssessResult) {
            this.MovieAssessResult = MovieAssessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Message_comingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Message_coming", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.Message_comingRequestBody Body;
        
        public Message_comingRequest() {
        }
        
        public Message_comingRequest(CSharp_FinalWork.WebService.Message_comingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Message_comingRequestBody {
        
        public Message_comingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Message_comingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Message_comingResponse", Namespace="http://tempuri.org/", Order=0)]
        public CSharp_FinalWork.WebService.Message_comingResponseBody Body;
        
        public Message_comingResponse() {
        }
        
        public Message_comingResponse(CSharp_FinalWork.WebService.Message_comingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Message_comingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSharp_FinalWork.WebService.ArrayOfModel_movies_coming Message_comingResult;
        
        public Message_comingResponseBody() {
        }
        
        public Message_comingResponseBody(CSharp_FinalWork.WebService.ArrayOfModel_movies_coming Message_comingResult) {
            this.Message_comingResult = Message_comingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : CSharp_FinalWork.WebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CSharp_FinalWork.WebService.WebServiceSoap>, CSharp_FinalWork.WebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharp_FinalWork.WebService.MessageResponse CSharp_FinalWork.WebService.WebServiceSoap.Message(CSharp_FinalWork.WebService.MessageRequest request) {
            return base.Channel.Message(request);
        }
        
        public CSharp_FinalWork.WebService.ArrayOfModel_movies Message() {
            CSharp_FinalWork.WebService.MessageRequest inValue = new CSharp_FinalWork.WebService.MessageRequest();
            inValue.Body = new CSharp_FinalWork.WebService.MessageRequestBody();
            CSharp_FinalWork.WebService.MessageResponse retVal = ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).Message(inValue);
            return retVal.Body.MessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MessageResponse> CSharp_FinalWork.WebService.WebServiceSoap.MessageAsync(CSharp_FinalWork.WebService.MessageRequest request) {
            return base.Channel.MessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MessageResponse> MessageAsync() {
            CSharp_FinalWork.WebService.MessageRequest inValue = new CSharp_FinalWork.WebService.MessageRequest();
            inValue.Body = new CSharp_FinalWork.WebService.MessageRequestBody();
            return ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).MessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharp_FinalWork.WebService.MessageDetailResponse CSharp_FinalWork.WebService.WebServiceSoap.MessageDetail(CSharp_FinalWork.WebService.MessageDetailRequest request) {
            return base.Channel.MessageDetail(request);
        }
        
        public CSharp_FinalWork.WebService.model_detail MessageDetail(string link, int tag) {
            CSharp_FinalWork.WebService.MessageDetailRequest inValue = new CSharp_FinalWork.WebService.MessageDetailRequest();
            inValue.Body = new CSharp_FinalWork.WebService.MessageDetailRequestBody();
            inValue.Body.link = link;
            inValue.Body.tag = tag;
            CSharp_FinalWork.WebService.MessageDetailResponse retVal = ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).MessageDetail(inValue);
            return retVal.Body.MessageDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MessageDetailResponse> CSharp_FinalWork.WebService.WebServiceSoap.MessageDetailAsync(CSharp_FinalWork.WebService.MessageDetailRequest request) {
            return base.Channel.MessageDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MessageDetailResponse> MessageDetailAsync(string link, int tag) {
            CSharp_FinalWork.WebService.MessageDetailRequest inValue = new CSharp_FinalWork.WebService.MessageDetailRequest();
            inValue.Body = new CSharp_FinalWork.WebService.MessageDetailRequestBody();
            inValue.Body.link = link;
            inValue.Body.tag = tag;
            return ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).MessageDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharp_FinalWork.WebService.RelatedMoviesResponse CSharp_FinalWork.WebService.WebServiceSoap.RelatedMovies(CSharp_FinalWork.WebService.RelatedMoviesRequest request) {
            return base.Channel.RelatedMovies(request);
        }
        
        public CSharp_FinalWork.WebService.ArrayOfModel_moviecrude RelatedMovies(string link) {
            CSharp_FinalWork.WebService.RelatedMoviesRequest inValue = new CSharp_FinalWork.WebService.RelatedMoviesRequest();
            inValue.Body = new CSharp_FinalWork.WebService.RelatedMoviesRequestBody();
            inValue.Body.link = link;
            CSharp_FinalWork.WebService.RelatedMoviesResponse retVal = ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).RelatedMovies(inValue);
            return retVal.Body.RelatedMoviesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.RelatedMoviesResponse> CSharp_FinalWork.WebService.WebServiceSoap.RelatedMoviesAsync(CSharp_FinalWork.WebService.RelatedMoviesRequest request) {
            return base.Channel.RelatedMoviesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSharp_FinalWork.WebService.RelatedMoviesResponse> RelatedMoviesAsync(string link) {
            CSharp_FinalWork.WebService.RelatedMoviesRequest inValue = new CSharp_FinalWork.WebService.RelatedMoviesRequest();
            inValue.Body = new CSharp_FinalWork.WebService.RelatedMoviesRequestBody();
            inValue.Body.link = link;
            return ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).RelatedMoviesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharp_FinalWork.WebService.MovieAssessResponse CSharp_FinalWork.WebService.WebServiceSoap.MovieAssess(CSharp_FinalWork.WebService.MovieAssessRequest request) {
            return base.Channel.MovieAssess(request);
        }
        
        public CSharp_FinalWork.WebService.ArrayOfString MovieAssess(string link) {
            CSharp_FinalWork.WebService.MovieAssessRequest inValue = new CSharp_FinalWork.WebService.MovieAssessRequest();
            inValue.Body = new CSharp_FinalWork.WebService.MovieAssessRequestBody();
            inValue.Body.link = link;
            CSharp_FinalWork.WebService.MovieAssessResponse retVal = ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).MovieAssess(inValue);
            return retVal.Body.MovieAssessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MovieAssessResponse> CSharp_FinalWork.WebService.WebServiceSoap.MovieAssessAsync(CSharp_FinalWork.WebService.MovieAssessRequest request) {
            return base.Channel.MovieAssessAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSharp_FinalWork.WebService.MovieAssessResponse> MovieAssessAsync(string link) {
            CSharp_FinalWork.WebService.MovieAssessRequest inValue = new CSharp_FinalWork.WebService.MovieAssessRequest();
            inValue.Body = new CSharp_FinalWork.WebService.MovieAssessRequestBody();
            inValue.Body.link = link;
            return ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).MovieAssessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSharp_FinalWork.WebService.Message_comingResponse CSharp_FinalWork.WebService.WebServiceSoap.Message_coming(CSharp_FinalWork.WebService.Message_comingRequest request) {
            return base.Channel.Message_coming(request);
        }
        
        public CSharp_FinalWork.WebService.ArrayOfModel_movies_coming Message_coming() {
            CSharp_FinalWork.WebService.Message_comingRequest inValue = new CSharp_FinalWork.WebService.Message_comingRequest();
            inValue.Body = new CSharp_FinalWork.WebService.Message_comingRequestBody();
            CSharp_FinalWork.WebService.Message_comingResponse retVal = ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).Message_coming(inValue);
            return retVal.Body.Message_comingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSharp_FinalWork.WebService.Message_comingResponse> CSharp_FinalWork.WebService.WebServiceSoap.Message_comingAsync(CSharp_FinalWork.WebService.Message_comingRequest request) {
            return base.Channel.Message_comingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSharp_FinalWork.WebService.Message_comingResponse> Message_comingAsync() {
            CSharp_FinalWork.WebService.Message_comingRequest inValue = new CSharp_FinalWork.WebService.Message_comingRequest();
            inValue.Body = new CSharp_FinalWork.WebService.Message_comingRequestBody();
            return ((CSharp_FinalWork.WebService.WebServiceSoap)(this)).Message_comingAsync(inValue);
        }
    }
}
